var button = document.querySelector('button');

var passageArray = [
'Gifted in anything that required analytical thinking, Stallman gravitated toward math and science at the expense of his other studies. What some teachers saw as single-mindedness, ' +
'however, Lippman saw as impatience. Math and science offered simply too much opportunity to learn, especially in comparison to subjects and pursuits for which her son seemed less ' +
'naturally inclined. Around age 10 or 11, when the boys in Stallman\'s class began playing a regular game of touch football, she remembers her son coming home in a rage. When he ' +
'wasn\'t working on official projects such as Sussman\'s automated circuit-analysis program, Stallman devoted his time to pet projects. It was in a hacker\'s best interest to improve ' +
'the lab\'s software infrastructure, and one of Stallman\'s biggest pet projects during this period was the lab\'s editor program TECO. In 1962, computer scientists and hackers involved ' +
'in MIT\'s Project MAC, an early forerunner of the AI Lab, took steps to alleviate this frustration. Time-sharing, originally known as "time stealing," made it possible for multiple ' +
'programs to take advantage of a machine\'s operational capabilities. Teletype interfaces also made it possible to communicate with a machine not through a series of punched holes ' +
'but through actual text. A programmer typed in commands and read the line-by-line output generated by the machine.',

'The word "home" is a weighted term in the Stallman lexicon. In a pointed swipe at his parents, Stallman, to this day, refuses to acknowledge any home before Currier House, the dorm ' +
'he lived in during his days at Harvard. He has also been known to describe leaving that home in tragicomic terms. Once, while describing his years at Harvard, Stallman said his only ' +
'regret was getting kicked out. It wasn\'t until I asked Stallman what precipitated his ouster, that I realized I had walked into a classic Stallman setup line. Although it meant ' +
'courting more run-ins at school, Lippman decided to indulge her son\'s passion. By age 12, Richard was attending science camps during the summer and private school during the school ' +
'year. When a teacher recommended her son enroll in the Columbia Science Honors Program, a post-Sputnik program designed for gifted middle and high-school students in New York City, ' +
'Stallman added to his extracurriculars and was soon commuting uptown to the Columbia University campus on Saturdays.',

'A populated rack accelerates the visible. The measured supernatural dances under a running shade. A toad blinks into the biography. Without the arc chalks any club. The obsolete ' +
'password connects with the model. Can a species deserve an applicant? An agony pardons a coach. The corpse accents the sexist designer without this cuckoo. A weekday bundle toes ' +
'the line. Outside the alpha attitude vanishes each corporate track. The sequel aligns the chart. The redundant league surprises the chemical behind the presented process.' +
'A nominated software toes the line near a sentimental squeeze. A bundle instructs the dialect. The revolting peripheral enlightens the wren. The inaccessible ignorance packages the gender inside her falling case.' +
'After the household suffers a cave. How can the widespread satellite turn the presumed decade? The swallow tires the despair. A complaint locks the pedestrian temper under a cynic. Opposite the bulb composes the ' +
'extremist. Should an adjacent attempt repair my champion minor? The combat blames his following money without a life. Can a daily plaster comfort an established executive? How does the galaxy lie upon an owing ' +
'lunchtime? How will an inserted garbage rot? The syndicate counts against the sheep!'
];

var seconds = 60;
var randomArray = null;

var onClick = function() {
  var randomPassage = passageArray[Math.floor(Math.random() * passageArray.length)];
  passageArray = randomPassage.split(' ');

  var container = document.getElementById('container');
  document.body.removeChild(container);
  document.body.style.backgroundColor = 'white';
  document.body.style.display = 'block';

  var wrapperDiv = document.createElement('div');
  document.body.appendChild(wrapperDiv);
  wrapperDiv.className = 'wrapper';
  var timerDiv = document.createElement('div');
  timerDiv.className = 'timer';
  wrapperDiv.appendChild(timerDiv);
  timerDiv.innerHTML = '1:00';
  var passageDiv = document.createElement('div');
  passageDiv.className = 'passage';
  passageDiv.innerHTML = randomPassage;

  wrapperDiv.appendChild(passageDiv);
  var textArea = document.createElement('textarea');
  textArea.id = 'text';
  wrapperDiv.appendChild(textArea);
  textArea.addEventListener('keyup', onType);
};

button.addEventListener('click', onClick);

var seconds = 60;
var time = null;

function minusSecond () {
  if (seconds > 0) {
    seconds -= 1;
    var timer = document.querySelector('.timer');
    timer.innerHTML = '0:' + seconds;
    if (seconds <10)
      timer.innerHTML = '0:0' + seconds;
  }
  else {
    window.clearInterval(time);
    var wrapperDiv = document.querySelector('.wrapper');
    document.body.removeChild(wrapperDiv);
    document.body.style.backgroundColor = 'rgb(179, 210, 181)';
    document.body.style.display = 'flex';
    var container = document.createElement('div');
    container.id = 'container';
    container.style.height = '200px';
    container.style.width = '430px';
    document.body.appendChild(container);
    var result = document.createElement('h3');
    container.appendChild(result);
    var wpm = document.createElement('p');
    container.appendChild(wpm);
    var again = document.createElement('h6');
    container.appendChild(again);
    result.innerHTML = 'Result:';
    wpm.innerHTML = 'You got ' + correctWords + ' words per minute!';
    h3.innerHTML = '<a href="http://rachelmcquirk.come/projects/typetest">Try Again?</a>';
  }
}

var correctWords = null;

var onType = function() {
  var words = this.value;
  if (!time)
    time = setInterval(minusSecond, 1000);
  var wordsArray = words.split(' ');
  correctWords = 0;
  for (var i = 0; i < wordsArray.length; i++) {
    if (wordsArray[i] === passageArray[i])
      correctWords += 1;
      console.log(wordsArray[i]);
  }
};

// var results = function() {
//   for(var i = 0; i < words.length; )
// };
